[package]
name = "gvas"
description = "Crate for parsing UE4 gvas save files."
authors = ["localcc <work@localcc.cc>"]
keywords = ["ue4", "unrealengine", "ue5", "gvas", "uasset"]
homepage = "https://github.com/localcc/gvas"
repository = "https://github.com/localcc/gvas"
readme = "README.md"
license = "MIT"
version = "0.2.5"
edition = "2021"

[dependencies]
enum_dispatch = "0.3.8"
byteorder = "1.4.3"
ordered-float = "3.4.0"
serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
serde = ["dep:serde", "ordered-float/serde"]
